name: firebase_messaging_poc
description: >
  Just a single short paragraph. 
  This Flutter app is a practical tool for testing Firebase push notifications, 
  offering developers a hands-on experience with real-time notifications, 
  FCM token management, and provider-based state management, all within a 
  clean and user-friendly interface.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
