// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3KwzPI_wVBfvOdvXjdVBAH2jxn_riOAk',
    appId: '1:562310470354:android:b8a162b926a2ac4a616b0b',
    messagingSenderId: '562310470354',
    projectId: 'fir-messagingpoc-a2170',
    storageBucket: 'fir-messagingpoc-a2170.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa18IvNT8TDT4twplqaQkM70X46j-oXxk',
    appId: '1:562310470354:web:d7bbdf97564ba2cd616b0b',
    messagingSenderId: '562310470354',
    projectId: 'fir-messagingpoc-a2170',
    authDomain: 'fir-messagingpoc-a2170.firebaseapp.com',
    storageBucket: 'fir-messagingpoc-a2170.appspot.com',
    measurementId: 'G-YNNSGMSPNW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00z-NSS-G0Xc19i2BuGXFNi1NDl2BxYk',
    appId: '1:562310470354:ios:0f388b349d41813c616b0b',
    messagingSenderId: '562310470354',
    projectId: 'fir-messagingpoc-a2170',
    storageBucket: 'fir-messagingpoc-a2170.appspot.com',
    iosBundleId: 'com.example.firebaseMessagingPoc',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00z-NSS-G0Xc19i2BuGXFNi1NDl2BxYk',
    appId: '1:562310470354:ios:0f388b349d41813c616b0b',
    messagingSenderId: '562310470354',
    projectId: 'fir-messagingpoc-a2170',
    storageBucket: 'fir-messagingpoc-a2170.appspot.com',
    iosBundleId: 'com.example.firebaseMessagingPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa18IvNT8TDT4twplqaQkM70X46j-oXxk',
    appId: '1:562310470354:web:2362806bf01f0787616b0b',
    messagingSenderId: '562310470354',
    projectId: 'fir-messagingpoc-a2170',
    authDomain: 'fir-messagingpoc-a2170.firebaseapp.com',
    storageBucket: 'fir-messagingpoc-a2170.appspot.com',
    measurementId: 'G-EDRFZWHFE6',
  );

}